// <auto-generated />
namespace API.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_country_and_city : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_country_and_city));
        
        string IMigrationMetadata.Id
        {
            get { return "201609242043217_added_country_and_city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
